{% set name = "concurrent-log-handler" %}
{% set version = "0.9.19" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b12f79abed3f94121c25ce9c24cdb57d889282ec6ff61f5535ab2068dc37d409
  patches:
    - 0001-Removed-ez_setup-from-the-setup-process.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    # Add minimum run constraint since in py2 there is an upper bound on portalocker
    - python >=3.6
    - portalocker >=1.4.0

test:
  imports:
    - concurrent_log_handler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Preston-Landers/concurrent-log-handler
  summary: RotatingFileHandler replacement with concurrency, gzip and Windows support
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
